name: Docker Image CI

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flamapy/flamapy-fm-dist:$(date +%s)
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_API_TOKEN }}
    - name: Push the Docker image
      run: docker push flamapy/flamapy-fm-dist:$(date +%s)
